name: "Auto merge"
on:
  pull_request:
    types: [edited]
    branches: [main]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: 8BitJonny/gh-get-current-pr@1.3.0
      id: get_pr_data
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ github.event.pull_request.head.sha }}
        filterOutClosed: true
    - name: Getting PRs
      id: get_pulls
      uses: octokit/request-action@v2.1.0
      with:
        route: GET /repos/${{ github.repository }}/pulls
        state: open
        base: ${{ github.base_ref }}
        head: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check of Completion
      id: check_of_completion
      run: |
        length=$(echo '${{ steps.get_pulls.outputs.data }}' | jq -r '. | length')
        if [ $length != "1" ]; then
          exit 1
        fi

        body=$(echo '${{ steps.get_pulls.outputs.data }}' | jq -r '.[0].body')
        incomplete_task=$(echo $body | sed -n "/\- \[ \]/ p")
        if [ -z $incomplete_task ]; then
          echo "::set-output name=completed::true"
        else
          echo "::set-output name=completed::false"
        fi
    - run: echo "Perform merge steps"
      if: ${{ steps.check_of_completion.outputs.completed == 'true' }}
    - name: Checkout develop
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Configure Git
      run: |
        git config user.email "git@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        git fetch
    - name: Merge to develop
      run: |
        git checkout ${{ github.event.pull_request.head.sha }} -b ${{ github.head_ref }}
        git checkout develop
        git merge ${{ github.head_ref }} --no-ff -m "Merge ${{ github.head_ref }} into develop"
        git push
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Merge to main
      run: |
        git merge ${{ github.head_ref }} --no-ff -m "Merge ${{ github.head_ref }} into main"
        git push
