name: "Git-flow merge"
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout develop
      uses: actions/checkout@v2
      with:
        ref: develop
    - run: git fetch
    - name: Merge to develop
      run: |
        git merge remotes/origin/${{ github.head_ref }} --no-ff -m "Merge ${{ github.head_ref }} into develop"
        git push
