name: "Git-flow merge"
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout develop
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Configure Git
      run: |
        git config user.email "git@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        git fetch
    - name: Merge to develop
      run: |
        git checkout ${{ github.event.pull_request.head.sha }} -b ${{ github.head_ref }}
        git checkout develop
        git merge ${{ github.head_ref }} --no-ff -m "Merge ${{ github.head_ref }} into develop"
        git push
    - name: Merge to main
      run: |
        git checkout ref/origin/master
        git merge ${{ github.head_ref }} --no-ff -m "Merge ${{ github.head_ref }} into main"
        git push
