name: "Git-flow merge"
on:
  pull_request:
    types: [closed]
    # branches: [main]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: github.event.pull_request.merged == true
    steps:
    # - name: Configure Git
    #   run: |
    #     git config user.email "git@users.noreply.github.com"
    #     git config user.name "github actions"
    - name: Checkout develop
      uses: actions/checkout@v2
      with:
        ref: develop
    - run: git fetch
    - name: Merge to develop
      run: |
        git merge remotes/origin/${{ github.head_ref }} --no-ff -m "Merge ${{ github.head_ref }} into develop"
        git push
