name: "Git-flow merge"
on:
  pull_request:
    types: [edited]
    branches: [master]

jobs:
  check_that_current_pr_is_complete:
    if: ${{ github.repository != 'plaidev/karte-ios-sdk' && github.event.pull_request.state == 'open' }}
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      completed: ${{ steps.check_completion.outputs.completed }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GH_ACCESS_TOKEN }}
        all_but_latest: true
    - name: Check Completion
      id: check_completion
      run: |
        body=$(echo '${{ github.event.pull_request.body }}')
        incomplete_task=$(echo $body | sed -n "/\- \[ \]/ p")
        if [ -z $incomplete_task ]; then
            echo "::set-output name=completed::true"
        else
            echo "::set-output name=completed::false"
        fi

  perform_merge:
    permissions:
      contents: write
    needs: [check_that_current_pr_is_complete]
    runs-on: ubuntu-latest
    if: needs.check_that_current_pr_is_complete.outputs.completed == 'true'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: echo "hoge"
