name: "Get Ready for Release"
on:
  push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: fastlane
      run: |
        bundle install --path ./vendor/bundle
        bundle exec fastlane sample

