name: "Get Ready for Release"
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Check branches
      run: |
        if [ $GITHUB_REF_NAME != "develop" ]; then
          exit 1
        end
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.7.0
      with:
        title: Deploy to production by ${{ github.actor }}
        branch: release/${{ steps.date.outputs.date }}
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        base: master
        token: ${{ secrets.GITHUB }}
