name: "Create XCFramework and Deploy Swift-PM"
on:
  push:
    branches:
    - release/*
    - hotfix/*

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: main
