name: "Create XCFramework and Deploy Swift-PM"
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.head_ref }}
    - run: |
        git config user.email "git@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        echo "run on gh actions" >> test.txt
        git add .
        git co -m "co"
        git push
